/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authBlankRouteRouteImport } from './routes/(auth)/_blank/route'
import { Route as authBlankRegisterRouteImport } from './routes/(auth)/_blank/register'
import { Route as authBlankLoginRouteImport } from './routes/(auth)/_blank/login'
import { Route as authBlankForgotPasswordRouteImport } from './routes/(auth)/_blank/forgot-password'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authBlankRouteRoute = authBlankRouteRouteImport.update({
  id: '/(auth)/_blank',
  getParentRoute: () => rootRouteImport,
} as any)
const authBlankRegisterRoute = authBlankRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authBlankRouteRoute,
} as any)
const authBlankLoginRoute = authBlankLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authBlankRouteRoute,
} as any)
const authBlankForgotPasswordRoute = authBlankForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authBlankRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof authBlankForgotPasswordRoute
  '/login': typeof authBlankLoginRoute
  '/register': typeof authBlankRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authBlankForgotPasswordRoute
  '/login': typeof authBlankLoginRoute
  '/register': typeof authBlankRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/_blank': typeof authBlankRouteRouteWithChildren
  '/(auth)/_blank/forgot-password': typeof authBlankForgotPasswordRoute
  '/(auth)/_blank/login': typeof authBlankLoginRoute
  '/(auth)/_blank/register': typeof authBlankRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/forgot-password' | '/login' | '/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/forgot-password' | '/login' | '/register'
  id:
    | '__root__'
    | '/'
    | '/(auth)/_blank'
    | '/(auth)/_blank/forgot-password'
    | '/(auth)/_blank/login'
    | '/(auth)/_blank/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authBlankRouteRoute: typeof authBlankRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_blank': {
      id: '/(auth)/_blank'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authBlankRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_blank/register': {
      id: '/(auth)/_blank/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authBlankRegisterRouteImport
      parentRoute: typeof authBlankRouteRoute
    }
    '/(auth)/_blank/login': {
      id: '/(auth)/_blank/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authBlankLoginRouteImport
      parentRoute: typeof authBlankRouteRoute
    }
    '/(auth)/_blank/forgot-password': {
      id: '/(auth)/_blank/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authBlankForgotPasswordRouteImport
      parentRoute: typeof authBlankRouteRoute
    }
  }
}

interface authBlankRouteRouteChildren {
  authBlankForgotPasswordRoute: typeof authBlankForgotPasswordRoute
  authBlankLoginRoute: typeof authBlankLoginRoute
  authBlankRegisterRoute: typeof authBlankRegisterRoute
}

const authBlankRouteRouteChildren: authBlankRouteRouteChildren = {
  authBlankForgotPasswordRoute: authBlankForgotPasswordRoute,
  authBlankLoginRoute: authBlankLoginRoute,
  authBlankRegisterRoute: authBlankRegisterRoute,
}

const authBlankRouteRouteWithChildren = authBlankRouteRoute._addFileChildren(
  authBlankRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authBlankRouteRoute: authBlankRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
